### ISSUE TITLE
License for the materials of this repo

### ISSUE THREAD

**Issue by rskikuli** [OpenLabsHackerspace/Wikimedia-Hackathon-2020#1]
We are working on the visual ID of the hackathon and I was wondering about your proposal on the license we should publish the materials.

**Comment by AnXh3L0** [comment]
CC BY SA NC 4.0 is my proposal

**Comment by rskikuli** [comment]
Thanks @AnXh3L0 . Assigning @sidorelauku here for the change.

**Comment by sidorelauku** [comment]
I added CC BY SA 4.0 license, as cc-by-sa-nc-4.0 is not compatible with Wikimedia Commons.

**Comment by rskikuli** [comment]
Thank you both. Closing this.
